host: localhost

default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: DJ_database_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: DJ_database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: DJ_database_production
  pool: 5
  timeout: 5000
